// +build !ignore_autogenerated

/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventProperties) DeepCopyInto(out *CloudEventProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventProperties.
func (in *CloudEventProperties) DeepCopy() *CloudEventProperties {
	if in == nil {
		return nil
	}
	out := new(CloudEventProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubFork) DeepCopyInto(out *GitHubFork) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubFork.
func (in *GitHubFork) DeepCopy() *GitHubFork {
	if in == nil {
		return nil
	}
	out := new(GitHubFork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubPullRequest) DeepCopyInto(out *GitHubPullRequest) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubPullRequest.
func (in *GitHubPullRequest) DeepCopy() *GitHubPullRequest {
	if in == nil {
		return nil
	}
	out := new(GitHubPullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubPush) DeepCopyInto(out *GitHubPush) {
	*out = *in
	out.CloudEventProperties = in.CloudEventProperties
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubPush.
func (in *GitHubPush) DeepCopy() *GitHubPush {
	if in == nil {
		return nil
	}
	out := new(GitHubPush)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSource) DeepCopyInto(out *GitHubSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSource.
func (in *GitHubSource) DeepCopy() *GitHubSource {
	if in == nil {
		return nil
	}
	out := new(GitHubSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSourceList) DeepCopyInto(out *GitHubSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitHubSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSourceList.
func (in *GitHubSourceList) DeepCopy() *GitHubSourceList {
	if in == nil {
		return nil
	}
	out := new(GitHubSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSourceSpec) DeepCopyInto(out *GitHubSourceSpec) {
	*out = *in
	in.EventTypes.DeepCopyInto(&out.EventTypes)
	in.AccessToken.DeepCopyInto(&out.AccessToken)
	in.SecretToken.DeepCopyInto(&out.SecretToken)
	if in.Sink != nil {
		in, out := &in.Sink, &out.Sink
		*out = new(v1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSourceSpec.
func (in *GitHubSourceSpec) DeepCopy() *GitHubSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubSourceStatus) DeepCopyInto(out *GitHubSourceStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubSourceStatus.
func (in *GitHubSourceStatus) DeepCopy() *GitHubSourceStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubEventTypes) DeepCopyInto(out *GithubEventTypes) {
	*out = *in
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(GitHubPullRequest)
		**out = **in
	}
	if in.Push != nil {
		in, out := &in.Push, &out.Push
		*out = new(GitHubPush)
		**out = **in
	}
	if in.Fork != nil {
		in, out := &in.Fork, &out.Fork
		*out = new(GitHubFork)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubEventTypes.
func (in *GithubEventTypes) DeepCopy() *GithubEventTypes {
	if in == nil {
		return nil
	}
	out := new(GithubEventTypes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretValueFromSource) DeepCopyInto(out *SecretValueFromSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretValueFromSource.
func (in *SecretValueFromSource) DeepCopy() *SecretValueFromSource {
	if in == nil {
		return nil
	}
	out := new(SecretValueFromSource)
	in.DeepCopyInto(out)
	return out
}
