# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
  name: bitbucketsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: BitBucketSource
    plural: bitbucketsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            consumerKey:
              properties:
                secretKeyRef:
                  type: object
              type: object
            eventTypes:
              items:
                enum:
                - repo:push
                - repo:fork
                - repo:updated
                - repo:commit_comment_created
                - repo:commit_status_created
                - repo:commit_status_updated
                - pullrequest:created
                - pullrequest:updated
                - pullrequest:approved
                - pullrequest:unapproved
                - pullrequest:fulfilled
                - pullrequest:rejected
                - pullrequest:comment_created
                - pullrequest:comment_updated
                - pullrequest:comment_deleted
                - issue:created
                - issue:updated
                - issue:comment_created
                type: string
              minItems: 1
              type: array
            ownerAndRepository:
              minLength: 1
              type: string
            consumerSecret:
              properties:
                secretKeyRef:
                  type: object
              type: object
            serviceAccountName:
              type: string
            sink:
              type: object
          required:
          - ownerAndRepository
          - eventTypes
          - consumerKey
          - consumerSecret
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    # we use a string in the stored object but a wrapper object
                    # at runtime.
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
            webhookUUIDKey:
              type: string
          type: object
  version: v1alpha1

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.repo-push
spec:
  type: dev.knative.source.bitbucket.repo:push
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.repo-fork
spec:
  type: dev.knative.source.bitbucket.repo:fork
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.repo-updated
spec:
  type: dev.knative.source.bitbucket.repo:updated
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.repo-commit-comment-created
spec:
  type: dev.knative.source.bitbucket.repo:commit_comment_created
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.repo-commit-status-created
spec:
  type: dev.knative.source.bitbucket.repo:commit_status_created
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.repo-commit-status-updated
spec:
  type: dev.knative.source.bitbucket.repo:commit_status_updated
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-created
spec:
  type: dev.knative.source.bitbucket.pullrequest:created
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-updated
spec:
  type: dev.knative.source.bitbucket.pullrequest:updated
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-approved
spec:
  type: dev.knative.source.bitbucket.pullrequest:approved
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-unapproved
spec:
  type: dev.knative.source.bitbucket.pullrequest:unapproved
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-fulfilled
spec:
  type: dev.knative.source.bitbucket.pullrequest:fulfilled
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-rejected
spec:
  type: dev.knative.source.bitbucket.pullrequest:rejected
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-comment-created
spec:
  type: dev.knative.source.bitbucket.pullrequest:comment_created
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-comment-updated
spec:
  type: dev.knative.source.bitbucket.pullrequest:comment_updated
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.pullrequest-comment-deleted
spec:
  type: dev.knative.source.bitbucket.pullrequest:comment_deleted
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.issue-created
spec:
  type: dev.knative.source.bitbucket.issue:created
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.issue-updated
spec:
  type: dev.knative.source.bitbucket.issue:updated
  origin: bitbucket.org

---

apiVersion: eventing.knative.dev/v1alpha1
kind: EventType
metadata:
  name: dev.knative.source.bitbucket.issue-comment-created
spec:
  type: dev.knative.source.bitbucket.issue:comment_created
  origin: bitbucket.org

---