/*
Copyright 2019 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package resources

import (
	"fmt"
	"regexp"
	"strings"

	eventingv1alpha1 "github.com/knative/eventing/pkg/apis/eventing/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/validation"
)

const (
	// Label to get the event types generated by a particular object.
	eventingEventTypeLabelKey = "eventing.knative.dev/eventtype"
)

var (
	// Only allow alphanumeric, '-' or '.'.
	validChars = regexp.MustCompile(`[^-\.a-z0-9]+`)
)

func MakeEventType(crd v1beta1.CustomResourceDefinition, namespace *corev1.Namespace, eventType string) eventingv1alpha1.EventType {
	return eventingv1alpha1.EventType{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: fmt.Sprintf("%s-", toValidIdentifier(eventType)),
			Labels:       eventTypeLabels(crd.Name),
			Namespace:    namespace.Name,
		},
		Spec: eventingv1alpha1.EventTypeSpec{
			Type: eventType,
			From: strings.ToLower(crd.Spec.Names.Kind),
			// TODO should have schema in the CRD?
			Schema: "",
		},
	}
}

func toValidIdentifier(eventType string) string {
	if msgs := validation.IsDNS1123Subdomain(eventType); len(msgs) != 0 {
		// If it is not a valid DNS1123 name, make it a valid one.
		// TODO take care of size < 63, and starting and end indexes should be alphanumeric.
		eventType = strings.ToLower(eventType)
		eventType = validChars.ReplaceAllString(eventType, "")
	}
	return eventType
}

func eventTypeLabels(objName string) map[string]string {
	return map[string]string{
		eventingEventTypeLabelKey: objName,
	}
}
